import { type FormEvent, useState } from 'react'
import { Link } from 'react-router-dom'
import { AuthLayout } from '../../../components/auth/AuthLayout'
import { RoleSelector } from '../../../components/auth/RoleSelector'
import { getPasswordRules, signUp } from '../auth-service'
import type { SignUpData, User } from '../types'

const initialForm: SignUpData = { employeeId: '', email: '', password: '', confirmPassword: '', role: 'EMPLOYEE' }
export function SignUp() {
  const [form, setForm] = useState<SignUpData>(initialForm); const [error, setError] = useState(''); const [isSubmitting, setIsSubmitting] = useState(false); const [pendingUser, setPendingUser] = useState<User | null>(null)
  const update = <K extends keyof SignUpData>(field: K, value: SignUpData[K]) => { setForm((current) => ({ ...current, [field]: value })); setError('') }
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setIsSubmitting(true); setError(''); const result = await signUp(form); setIsSubmitting(false); if (!result.success || !result.user) { setError(result.message ?? 'Unable to create your account'); return }; setPendingUser(result.user) }
  if (pendingUser) return <AuthLayout eyebrow="Registration complete" title="Verify your email." description={`We've sent a verification link to ${pendingUser.email}.`}><div className="rounded-2xl bg-white p-6 shadow-[0_1px_3px_rgba(0,0,0,0.08)]"><p className="text-sm leading-6 text-zinc-500">This is a mock verification state. No email has been sent; connect a production authentication provider to deliver and validate email verification links.</p><Link to="/signin" className="mt-6 flex w-full justify-center rounded-xl bg-zinc-950 px-4 py-4 text-sm font-bold text-white hover:bg-zinc-800">Return to sign in</Link></div></AuthLayout>
  const passwordRules = getPasswordRules(form.password)
  return <AuthLayout eyebrow="Create your workspace" title="Join DayFlow." description="Set up your DayFlow access in a few moments."><form onSubmit={submit} className="space-y-4"><label className="block text-sm font-semibold">Employee ID<input required value={form.employeeId} onChange={(event) => update('employeeId', event.target.value)} placeholder="EMP-0001" className="mt-2 w-full rounded-xl bg-white px-4 py-3.5 text-sm shadow-[0_1px_3px_rgba(0,0,0,0.08)] outline-none ring-1 ring-zinc-200 focus:ring-2 focus:ring-zinc-950" /></label><label className="block text-sm font-semibold">Email<input required type="email" autoComplete="email" value={form.email} onChange={(event) => update('email', event.target.value)} placeholder="you@company.com" className="mt-2 w-full rounded-xl bg-white px-4 py-3.5 text-sm shadow-[0_1px_3px_rgba(0,0,0,0.08)] outline-none ring-1 ring-zinc-200 focus:ring-2 focus:ring-zinc-950" /></label><div><label className="block text-sm font-semibold">Password<input required type="password" autoComplete="new-password" value={form.password} onChange={(event) => update('password', event.target.value)} placeholder="Create a secure password" className="mt-2 w-full rounded-xl bg-white px-4 py-3.5 text-sm shadow-[0_1px_3px_rgba(0,0,0,0.08)] outline-none ring-1 ring-zinc-200 focus:ring-2 focus:ring-zinc-950" /></label><ul className="mt-2 grid grid-cols-1 gap-1 text-xs text-zinc-500">{passwordRules.map((rule) => <li key={rule.label} className={rule.isSatisfied ? 'font-semibold text-green-700' : ''}>{rule.isSatisfied ? '✓' : '○'} {rule.label}</li>)}</ul></div><label className="block text-sm font-semibold">Confirm password<input required type="password" autoComplete="new-password" value={form.confirmPassword} onChange={(event) => update('confirmPassword', event.target.value)} placeholder="Repeat your password" className="mt-2 w-full rounded-xl bg-white px-4 py-3.5 text-sm shadow-[0_1px_3px_rgba(0,0,0,0.08)] outline-none ring-1 ring-zinc-200 focus:ring-2 focus:ring-zinc-950" /></label><RoleSelector value={form.role} onChange={(role) => update('role', role)} />{error && <p role="alert" className="rounded-xl bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{error}</p>}<button disabled={isSubmitting} className="flex w-full justify-center rounded-xl bg-zinc-950 px-4 py-4 text-sm font-bold text-white hover:bg-zinc-800 disabled:cursor-not-allowed disabled:opacity-50">{isSubmitting ? 'Creating account...' : 'Create account'}</button></form><p className="mt-7 text-center text-sm text-zinc-500">Already have an account? <Link to="/signin" className="font-bold text-zinc-950 hover:underline">Sign in</Link></p></AuthLayout>
}
